mage-os/generate-mirror-repo-js

bin/set-satis-output-url-prefix.js

I'm trying to build it in a subdirectory, like `https://example.com/mirror`. The build script ends up crashing:
```
mirror-generator_1  | Writing packages.json
mirror-generator_1  | Pruning include directories
mirror-generator_1  | Writing web view
mirror-generator_1  | Setting url prefix in generated output to https://example.com/mirror...
mirror-generator_1  | node:internal/fs/utils:344
mirror-generator_1  |     throw err;
mirror-generator_1  |     ^
mirror-generator_1  |
mirror-generator_1  | Error: ENOENT: no such file or directory, open '/build/mirror/p2/amzn/amazon-pay-and-login-magento-2-module.json'
mirror-generator_1  |     at Object.openSync (node:fs:585:3)
mirror-generator_1  |     at Object.readFileSync (node:fs:453:35)
mirror-generator_1  |     at Object.<anonymous> …
```

Fix set-satis-output-url-prefix.js crashing when url has a subdirectory

---

src/build-config/mirror-build-config.js

MageOS:
```
$ composer show magento/adobe-stock-integration
<snip>
requires
magento/adobe-ims *
magento/module-adobe-stock-admin-ui *
magento/module-adobe-stock-asset *
magento/module-adobe-stock-asset-api *
magento/module-adobe-stock-client *
magento/module-adobe-stock-client-api *
magento/module-adobe-stock-image *
magento/module-adobe-stock-image-admin-ui *
magento/module-adobe-stock-image-api *
```
Magento:
```
$ composer show magento/adobe-stock-integration
<snip>
requires
magento/adobe-ims *
magento/module-adobe-stock-admin-ui 1.3.0-p1
magento/module-adobe-stock-asset 1.3.0-p1
magento/module-adobe-stock-asset-api 2.0.0-p1
magento/module-adobe-stock-client 1.3.1-p1
magento/module-adobe-stock-client-api 2.1.0-p1
magento/module-adobe-stock-image 1.3.1-p1 …
```

add adobe stock metapackage overrides for magento 2.4.3

---

resource/history/magento/product-community-edition/2.4.3.json

**DO NOT MERGE UNTIL https://github.com/magento/adobe-stock-integration/issues/1871 RESOLVED**
```
$ composer show magento/product-community-edition
name     : magento/product-community-edition
descrip. : eCommerce Platform for Growth (Community Edition)
keywords : 
versions : * 2.4.3
```
```
$ composer show magento/adobe-stock-integration
name     : magento/adobe-stock-integration
descrip. : Adobe Stock integration
keywords : 
versions : * 2.1.2
```

magento 2.4.3 should not use p1 version of adobe-stock-integration

---

src/build-config/mirror-build-config.js

Since we're building 100.3.7, which exists in tag 2.3.7.
2.3.7-p3 > 2.3.7 so it was never picked up.

lower magento2 fromTag

---

src/build-config/upstream-nightly-build-config.js
src/package-modules.js
src/release-branch-build-tools.js

Allow arbitrary transformation functions for the composer.json contents of specific nightly packages.  
This is required for to emulate what Adobe does in 2.4.6-beta1.  
See https://github.com/magento/magento2/issues/36687

[feat] Add composer config transformations

---

.github/workflows/deploy.yml

The warning shown in #36 comes from an outdated version of https://github.com/easingthemes/ssh-deploy. I shortly read through the release notes and did not find anything serious, I think it could / should just work. Not sure if we can test this before, but we could also merge, check and revert if it does not work.

Update ssh-deploy action, fixes #36

---

Dockerfile

The application depends on runtime JS dependencies, such as `parse-options`. These dependencies are nicely declared in package.json, but still need to be installed in the Docker image :).

Dockerfile: Run npm install

---

src/release-branch-build-tools.js
src/repository/shell-git.js

Nightly build is currently failing:
```
TypeError: Cannot read properties of undefined (reading 'substring')
at validateRefIsSecure (/home/runner/work/generate-mirror-repo-js/generate-mirror-repo-js/src/repository/shell-git.js:58:11)
at Object.listFolders (/home/runner/work/generate-mirror-repo-js/generate-mirror-repo-js/src/repository/shell-git.js:188:5)
at Object.listFolders (/home/runner/work/generate-mirror-repo-js/generate-mirror-repo-js/src/repository.js:12:16)
at findModulesToBuild (/home/runner/work/generate-mirror-repo-js/generate-mirror-repo-js/src/package-modules.js:406:30)
at determinePackagesForRef (/home/runner/work/generate-mirror-repo-js/generate-mirror-repo-js/src/package-modules.js:191:25)
at getPackagesForBuildInstruction …
```

fix: handle undefined reference caused by no tags on `commerce-data-export`

---

.github/workflows/build-mageos-release.yml

The `build-mageos-release` workflow is restricted to specific enumerated users. This would add me as one of them, if permitted, for the purpose of managing the Mage-OS 1.0.2 release.

chore: add rhoerr as an authorized deployer

---

src/release-build-tools.js

Fixes a regression in #154 where package name gets changed from `magento/...` to `{vendor}/...` before checking it against the `replaceVersionMap`. This causes it to find no match, because `replaceVersionMap` contains only `magento/...` package names.
This fixes it by recording the original package name before `composer.name = setMageOsVendor(...`, and using that for the map check.

fix: set package replace value by original package name

---

.github/workflows/build-mageos-release.yml
.github/workflows/build-upstream-mirror.yml

This PR adds @fballiano as an authorized deployer for Mage-OS releases and mirror deployments, on the basis of joining Mage-OS as Release Manager starting 1 Oct.
It also adds me @rhoerr to the mirror deployer list (missed in #167).

Add authorized mirror and release deployers

---

Dockerfile

while running `docker build .` we get 
`- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)`
This PR fixes it

Bugfix: FromAsCasing warning

---

resource/composer-templates/mage-os/magento2-base/template.json
resource/composer-templates/magento/magento2-base/template.json

The Mage-OS 1.0.5 release needs the tiny_mce_6 package added to the magento2-base module composer template, in order to copy to the proper location on install.
This PR adds that, and also adds tiny_mce_7 to the same for the upstream nightly builds -- because upstream has 7 packaged at this point.

Chore: fix tinymce map

---

.github/actions/checkout-magento/action.yml

This should solve the failing integrity checks for 2.4.4-p* but I've no way of testing it until it's merged.
Fixes https://github.com/mage-os/generate-mirror-repo-js/issues/186

Workaround for 2.4.4-p* integrity check

---

src/determine-dependencies.js
src/make/mageos-release.js
src/release-build-tools.js

This is the build-release portion of changes for https://github.com/mage-os/mageos-magento2/issues/108
Some extensions use version comparison in Magento to determine what code to run. This is a problem for Mage-OS, where we replace Magento's `getVersion()` number (IE 2.4.7) with the Mage-OS version (IE 1.0.5), causing old incompatible code to run.
The idea here is:
* Magento gets the version from composer.lock for `magento/product-community-edition`, via https://github.com/rhoerr/mageos-magento2/blob/7bed30c9ea2b6e31130d4cead3e191871fb9b98e/lib/internal/Magento/Framework/App/ProductMetadata.php#L118
* Mage-OS replaces that version number during our existing build/release process.
* To fix it, we change getVersion to return the equivalent Magento version, and add a separate method to get …

feat: add upstream version to metapackage composer.json for runtime use

---

README.md

This documentation was written during the process of releasing 2.4.7-p4 mirror.
To see a preview of the result: https://github.com/fballiano/mageos-generate-mirror-repo-js/tree/build-mirror?tab=readme-ov-file#process-of-building-a-new-mirror-release

Added documentation on how to build a new mirror release

---

resource/composer-templates/mage-os/product-community-edition/dependencies-template.json

I propose adding Creatuity_Interception as a bundled module with the upcoming Mage-OS 1.1.0. https://github.com/creatuity/magento2-interceptors
- It provides a meaningful and quantifiable performance improvement for all Magento Open Source sites, in the area of 10%;
- It is safe and battle tested, having been in frequent production use since 2019, including over 49k composer installs, and including all ParadoxLabs client sites I maintain;
- It is widely known and trusted;
- It is well maintained, with negligible open issues (rare or debatable edge cases).
- Mage-OS will have a new `compiled_plugins` cache type to be enabled or disabled on sites (optional opt-in)
- When enabled, compiling will result in interceptors being written into the generated/ folder with explicit calls to each …

Add creatuity/magento2-interceptors as a bundled extension

---

resource/history/mage-os/magento2-base/1.1.1.json
resource/history/mage-os/product-community-edition/1.1.1.json
resource/history/mage-os/project-community-edition/1.1.1.json

Adds release history files for Mage-OS Distro 1.1.1, in advance of 1.2.0 release.

chore: add release history for Mage-OS 1.1.1

---

src/package-modules.js

This is to resolve inconsistencies in the integrity test, such as https://github.com/mage-os/generate-mirror-repo-js/actions/runs/15568014814/job/43838800152

Skip generation of package versions that already exist for consistency with upstream

---

src/build-config/mirror-build-config.js

Patch 2.4.8-p1 project-community-edition mirror package composer.json to match upstream.
Goal: fix https://github.com/mage-os/generate-mirror-repo-js/actions/runs/15611641774/job/43975406891

Patch 2.4.8-p1 project-community-edition mirror package to match upstream

---

README.md
resource/history/mage-os/magento2-base/1.2.0.json
resource/history/mage-os/product-community-edition/1.2.0.json
resource/history/mage-os/project-community-edition/1.2.0.json

And a link to the versioning number RFC in the README

Added historical data about Mage-OS 1.2.0

---

resource/composer-templates/mage-os/product-community-edition/dependencies-template.json

I propose adding mage-os/module-meta-robots-tag as a bundled module. https://github.com/mage-os/module-meta-robots-tag
- Admins can set meta robots tags directly in the admin, on a per-entity basis, to manage crawl and indexing behavior.
- Enhanced SEO control without changes to theme or frontend performance.
- No workflow disruption; settings are updated through standard edit pages on the Magento admin UI.
- Improper use could impact SEO, so care is needed during use. But this isn't new, since robot tags can already be managed globally.
- Minimal risk overall since the module only adjusts meta tags.
- Improved SEO and control over search indexation for catalog and content pages.
- Quick, flexible adjustments to search engine directives as needed.
This PR results in the module being added …

Bundle mage-os/module-meta-robots-tag

---

resource/composer-templates/mage-os/product-community-edition/dependencies-template.json

I propose adding mage-os/module-inventory-reservations-grid as a bundled module. https://github.com/mage-os-lab/module-inventory-reservations-grid
- It provides a clear admin grid for Magento inventory reservations, improving visibility into reservation data.
- It is slim, purpose-built, and compatible with the latest Magento versions.
- It is maintained and focused on a single, important feature for inventory transparency.
- Admins gain direct access to view and manage inventory reservations via a dedicated grid in the admin panel.
- May reveal underlying issues with reservations or stock management that require process adjustments.
- No impact on frontend performance or customer experience, as all changes are on the backend.
- Potential for minor admin confusion if reservation data is …

Bundle mage-os/module-inventory-reservations-grid

---

resource/composer-templates/mage-os/product-community-edition/dependencies-template.json

I propose adding `mage-os-lab/module-pagebuilder-template-import-export` as a bundled module. [https://github.com/mage-os-lab/module-pagebuilder-template-import-export](https://github.com/mage-os-lab/module-pagebuilder-template-import-export)
- It provides import/export functionality for PageBuilder templates across instances.  
- It supports both local `.zip` template transfer and synchronization with Dropbox repositories.  
- It is maintained and has practical utility for agencies and merchants working with distributed content.  
- Merchants and agencies can standardize PageBuilder content across multiple stores without manually recreating it.  
- Admins will be able to pull and sync reusable templates from Dropbox repositories (with multi-repository support).  
- Shops leveraging …

Bundle mage-os/module-pagebuilder-template-import-export
